name: Deploy

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12.3'
    - name: Install pip and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        pip install lxml
        pip install pytest playwright
        playwright install
        pip install pandas
        pip install jmapc
        pip install apsw
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "app/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
